ProjetoTCC/Controllers/GeraPrestacoesController.cs
using Dapper;
using System;
using System.Data.Entity.Validation;
using System.Data.SqlClient;
using System.Linq;
using System.Threading;
using System.Web.Mvc;

namespace ProjetoTCC.Controllers
{
    [Authorize]
    public class GeraPrestacoesController : Controller
    {
        private EstudoTCCDB db = new EstudoTCCDB();

        public ActionResult GeraPrestacoes()
        {
            Dropdown();
            return View();
        }

        [HttpPost]
        public ActionResult GeraPrestacoes(int? Matricula, string Conta, string Chave, string PeriodoI, string PeriodoF, string TipoFiltro, string Faccao, bool PorGraduacao)
        {
            //Validações   
            if (string.IsNullOrEmpty(PeriodoI) || string.IsNullOrEmpty(PeriodoF))
            {
                TempData["warning"] = "Informe os períodos inicial e final";
                Dropdown();
                return View();
            }

            PeriodoI = PeriodoI.Replace("/", string.Empty);
            PeriodoF = PeriodoF.Replace("/", string.Empty);

            int x = Convert.ToInt32(PeriodoF);
            int y = Convert.ToInt32(PeriodoI);

            if (y > x)
            {
                TempData["error"] = "Período final deve ser inferior ou igual ao inicial";
                Dropdown();
                return View();
            }

            if (string.IsNullOrEmpty(Conta))
            {
                TempData["warning"] = "Selecione a conta para geração";
                Dropdown();
                return View();
            }

            if (string.IsNullOrEmpty(TipoFiltro))
            {
                TempData["warning"] = "Selecione um filtro";
                Dropdown();
                return View();
            }

            if (TipoFiltro == "PorMembro" && Matricula == null)
            {
                TempData["warning"] = "Selecione o membro de acordo com o filtro selecionado";
                Dropdown();
                return View();
            }

            if (TipoFiltro == "PorFaccao" && string.IsNullOrEmpty(Faccao))
            {
                TempData["warning"] = "Selecione a facção de acordo com o filtro selecionado";
                Dropdown();
                return View();
            }

            CalculaPeriodoEVencimento(PeriodoI, PeriodoF, out DateTime VencimentoInicial, out int f);

            string where = Where(TipoFiltro);

            GravaPrestacoes(Matricula, Conta, Chave, Faccao, VencimentoInicial, f, where, PorGraduacao);

            Dropdown();

            TempData["success"] = "Rotina de executada com sucesso";

            return RedirectToAction("Index", "Prestacoes");
        }


        /// <summary>
        /// Grava as prestações no banco de dados de acordo com o escopo do método CalculaPeriodoEVencimento.
        /// </summary>
        /// <param name="Matricula"></param>
        /// <param name="Conta"></param>
        /// <param name="Chave"></param>
        /// <param name="Faccao"></param>
        /// <param name="VencimentoInicial"></param>
        /// <param name="f"></param>
        /// <param name="where"></param>
        private void GravaPrestacoes(int? Matricula, string Conta, string Chave, string Faccao, DateTime VencimentoInicial, int f, string where, bool PorGraduacao)
        {
            using
            (
            var connection = new SqlConnection(Functions.Conexao())
            )
            {
                connection.Open();
                try
                {
                    var membros = connection
                        .Query<Membros>("SELECT Matricula, Graduacao FROM Membros(NOLOCK) WHERE " + where + ";",
                            new { Fac = Faccao, Mat = Matricula });

                    foreach (dynamic matricula in membros)
                    {
                        string ChavePrest = PorGraduacao? matricula.Graduacao : Chave;

                        for (int i = 0; i <= f; i++)
                        {
                            Prestacoes prest = new Prestacoes
                            {
                                Matricula = matricula.Matricula,
                                Conta = Conta,
                                Chave = ChavePrest,
                                Sequencia = VencimentoInicial.AddMonths(i).ToString("yyyyMM"),
                                DtVencimento = VencimentoInicial.AddMonths(i),
                                Situacao = "A",
                                Ass = "Criada pela geração de prestações em: " + DateTime.Now.ToString() + " por: " + User.Identity.Name
                            };

                            bool valido = Functions.ValidaPrestacao(matricula.Matricula, Conta, Chave, prest.DtVencimento);

                            if (valido)
                            {
                                db.Prestacoes.Add(prest);
                                db.SaveChanges();
                            }
                            else
                            {
                                var cts = new CancellationTokenSource();
                                cts.Dispose();
                            }
                        }
                    }
                }
                catch (DbEntityValidationException ex)
                {
                    foreach (var eve in ex.EntityValidationErrors)
                    {
                        Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                            eve.Entry.Entity.GetType().Name, eve.Entry.State);
                        foreach (var ve in eve.ValidationErrors)
                        {
                            Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"",
                                ve.PropertyName, ve.ErrorMessage);
                        }
                    }
                    throw;
                }
                finally
                {
                    connection.Close();
                }
            }
        }

        /// <summary>
        /// Retorna o vencimento da primeira prestação e a quantidade de repetições a serem geradas (f), a partir dos períodos inicial e final.
        /// </summary>
        /// <param name="PeriodoI"></param>
        /// <param name="PeriodoF"></param>
        /// <param name="VencimentoInicial"></param>
        /// <param name="f"></param>
        private static void CalculaPeriodoEVencimento(string PeriodoI, string PeriodoF, out DateTime VencimentoInicial, out int f)
        {
            // Separa o ano do mês do Periodo inicial
            string MesIni = PeriodoI.Substring(4, 2);
            string AnoIni = PeriodoI.Substring(0, 4);

            int AnoIniInt = Convert.ToInt32(AnoIni);
            int MesIniInt = Convert.ToInt32(MesIni);

            // Separa o ano do mês do Periodo final
            string MesFin = PeriodoF.Substring(4, 2);
            string AnoFin = PeriodoF.Substring(0, 4);

            int AnoFinInt = Convert.ToInt32(AnoFin);
            int MesFinInt = Convert.ToInt32(MesFin);

            // Primeiro vencimento da mensalidade é o dia 5 correspondendo ao período inicial
            VencimentoInicial = new DateTime(AnoIniInt, MesIniInt, 5);

            int a = (AnoFinInt - AnoIniInt) * 12;
            int b = Math.Abs(MesFinInt - MesIniInt);

            // Se o mês inicial for menor que o mês final, faz a soma, senão, faz subtração
            f = (MesIniInt < MesFinInt ? a + b : a - b);
        }

        // Monta a clausula Where da consulta
        private static string Where(string TipoFiltro)
        {
            string where = "";

            if (TipoFiltro == "PorFaccao")
            {
                where = "Faccao = @Fac";
            }
            if (TipoFiltro == "PorMembro")
            {
                where = "Matricula = @Mat";
            }
            if (TipoFiltro == "Todos")
            {
                where = "1=1";
            }
            return where;
        }

        private void Dropdown()
        {
            ViewBag.Matricula = new SelectList(db.Membros.Where(c => c.Inativo == false), "Matricula", "Nome");
            ViewBag.Chave = new SelectList(db.Chaves.Where(c => c.Inativo == false).Where(c => c.GeraConta == true), "Chave", "Chave");
            ViewBag.Faccao = new SelectList(db.Faccoes.Where(f => f.Inativo == false), "Chave", "Chave");
            ViewBag.Conta = db.Contas.Where(c => c.Inativo == false)
            .Select(c => new SelectListItem()
            {
                Text = c.Conta + " - " + c.Descricao,
                Value = c.Conta
            });
        }
    }
}

ProjetoTCC/Controllers/PrestacoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace ProjetoTCC.Controllers
{
    [Authorize]
    public class PrestacoesController : Controller
    {
        private EstudoTCCDB db = new EstudoTCCDB();

        // GET: Prestacoes
        public ActionResult Index()
        {
            return View(db.Prestacoes.ToList());
        }

        // GET: Prestacoes/Details/5
        public ActionResult Details(int? nrPrest)
        {
            if (nrPrest == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prestacoes prestacoes = db.Prestacoes.Find(nrPrest);
            if (prestacoes == null)
            {
                return HttpNotFound();
            }
            return View(prestacoes);
        }

        // GET: Prestacoes/Create
        public ActionResult Create()
        {
            Prestacoes prest = new Prestacoes();            
            prest.Sequencia = DateTime.Now.ToString("yyyyMM");
            prest.DtVencimento = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 5);
            Dropdown();
            ViewBag.NrPrest = new SelectList(db.Prestacoes).Count() + 1;
            return View(prest);
        }

        // POST: Prestacoes/Create
        [HttpPost]
        public ActionResult Create([Bind(Include = "nrprest,matricula,conta,chave,sequencia,valor,valorcalculado,dtvencimento,dtpagamento,situacao,formapagamento,obs,ass")] Prestacoes prest, string sequencia)
        {
            try
            {
                RemoveMascara(prest, sequencia);

                if (ModelState.IsValid)
                {
                    if (Functions.ValidaPrestacao(prest.Matricula, prest.Conta, prest.Chave, prest.DtVencimento))
                    {
                        prest.Ass = "Registro criado em " + DateTime.Now.ToString() + " por: " + User.Identity.Name;
                        db.Prestacoes.Add(prest);
                        db.SaveChanges();
                        TempData["success"] = "Prestação criada com sucesso";
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        TempData["warning"] = "Prestação já cadastrada";
                    }
                }
                Dropdown(prest);
            }
            catch (DbEntityValidationException e)
            {
                foreach (var eve in e.EntityValidationErrors)
                {
                    Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                        eve.Entry.Entity.GetType().Name, eve.Entry.State);
                    foreach (var ve in eve.ValidationErrors)
                    {
                        Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"",
                            ve.PropertyName, ve.ErrorMessage);
                    }
                }
                throw;
            }
            return View(prest);
        }

        // GET: Prestacoes/Edit/5
        public ActionResult Edit(int? nrPrest)
        {
            if (nrPrest == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prestacoes prestacoes = db.Prestacoes.Find(nrPrest);
            if (prestacoes == null)
            {
                return HttpNotFound();
            }
            Dropdown();
            return View(prestacoes);
        }

        // POST: Prestacoes/Edit/5
        [HttpPost]
        public ActionResult Edit([Bind(Include = "nrprest,matricula,conta,chave,sequencia,valor,valorcalculado,dtvencimento,dtpagamento,situacao,formapagamento,obs,ass")] Prestacoes prestacoes, string sequencia)
        {
            try
            {
                RemoveMascara(prestacoes, sequencia);
                prestacoes.Ass = "Registro editado em " + DateTime.Now.ToString() + " por: " + User.Identity.Name;                

                if (ModelState.IsValid)
                {
                    db.Entry(prestacoes).State = EntityState.Modified;
                    db.SaveChanges();
                    TempData["success"] = "Prestação editada com sucesso";
                    return RedirectToAction("Index");
                }
                Dropdown(prestacoes);
                return View();
            }
            catch (DbEntityValidationException e)
            {
                foreach (var eve in e.EntityValidationErrors)
                {
                    Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                        eve.Entry.Entity.GetType().Name, eve.Entry.State);
                    foreach (var ve in eve.ValidationErrors)
                    {
                        Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"",
                            ve.PropertyName, ve.ErrorMessage);
                    }
                }
                throw;
            }
        }

        // GET: Prestacoes/Delete/5
        public ActionResult Delete(int? nrPrest)
        {
            if (nrPrest == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prestacoes prestacoes = db.Prestacoes.Find(nrPrest);
            if (prestacoes == null)
            {
                return HttpNotFound();
            }
            return View(prestacoes);
        }

        // POST: Prestacoes/Delete/5
        [HttpPost]
        public ActionResult Delete(int nrPrest, FormCollection collection)
        {
            try
            {
                Prestacoes prestacoes = db.Prestacoes.Find(nrPrest);
                if (prestacoes.Situacao == "P")
                {
                    TempData["info"] = "Não é possível excluir uma prestação paga";
                }
                else
                {
                    db.Prestacoes.Remove(prestacoes);
                    db.SaveChanges();
                    TempData["success"] = "Prestação excluída com sucesso";
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        private void Dropdown()
        {
            ViewBag.Matricula = new SelectList(db.Membros.Where(c => c.Inativo == false), "Matricula", "Nome");
            ViewBag.FormaPagamento = new SelectList(db.FormaPagamento, "Tipo", "Descricao");
            ViewBag.Chave = new SelectList(db.Chaves.Where(c => c.Inativo == false).Where(c => c.GeraConta == true), "Chave", "Chave");
            ViewBag.Conta = db.Contas.Where(c => c.Inativo == false)
            .Select(c => new SelectListItem()
            {
                Text = c.Conta + " - " + c.Descricao,
                Value = c.Conta
            });

            ViewBag.Faccao = new SelectList(db.Faccoes.Where(f => f.Inativo == false), "Chave", "Chave");
            ViewBag.Situacao = new List<SelectListItem>
            {
                new SelectListItem {Text = "Em aberto", Value = "A"},
                new SelectListItem {Text = "Vencida", Value = "V"},
                new SelectListItem {Text = "Paga", Value = "P"},
                new SelectListItem {Text = "Anulada", Value = "N"}
            };
        }

        private void Dropdown(Prestacoes prestacoes)
        {
            ViewBag.Matricula = new SelectList(db.Membros.Where(c => c.Inativo == false), "Matricula", "Nome", prestacoes.Matricula);
            ViewBag.FormaPagamento = new SelectList(db.FormaPagamento, "Tipo", "Descricao", prestacoes.FormaPagamento);
            ViewBag.Chave = new SelectList(db.Chaves.Where(c => c.Inativo == false).Where(c => c.GeraConta == true), "Chave", "Chave", prestacoes.Chave);
            ViewBag.Conta = new SelectList(db.Contas.Where(c => c.Inativo == false), "Conta", "TipoChave", prestacoes.Conta);
            ViewBag.Faccao = new SelectList(db.Faccoes.Where(f => f.Inativo == false), "Chave", "Chave");
            ViewBag.Situacao = new List<SelectListItem>
            {
                new SelectListItem {Text = "Em aberto", Value = "A"},
                new SelectListItem {Text = "Vencido", Value = "V"},
                new SelectListItem {Text = "Pago", Value = "P"},
                new SelectListItem {Text = "Anulada", Value = "N"}
            };
        }

        private static void RemoveMascara(Prestacoes prestacoes, string sequencia)
        {
            prestacoes.Sequencia = sequencia.Replace("/", string.Empty);
        }

        public JsonResult BuscaChave(string Conta)
        {
            var json =
                from chaves in db.Chaves
                join contas in db.Contas on chaves.Tipo equals contas.Tipo
                where contas.Conta == Conta
                select new { chaves.Chave, chaves.Descricao };

            return Json(json, JsonRequestBehavior.AllowGet);
        }
    }
}

ProjetoTCC/Views/Prestacoes/Create.cshtml
@model ProjetoTCC.Prestacoes

@{
                /**/

                ViewBag.Title = "Criar";
}

<h2>Criar prestação</h2>
<nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-dark">
        <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Home", "Index", "Home")</a></li>
        <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Prestações", "Index", "Prestacoes")</a></li>
        <li class="breadcrumb-item active" aria-current="page">Membros</li>
    </ol>
</nav>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="row">
            <div class="col-lg">
                @Html.LabelFor(model => model.Matricula, htmlAttributes: new { @class = "control-label col" })
                <div class="col">
                    @Html.DropDownList("Matricula", null, "Selecione", htmlAttributes: new { @class = "form-control col-6" })
                    @Html.ValidationMessageFor(model => model.Matricula, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div>
            <div class="row">
                <div class="col">
                    @Html.LabelFor(model => model.Nrprest, "Prestação nº", htmlAttributes: new { @class = "control-label col" })
                    <div class="col-md-7">
                        <div class=" form-control " readonly>@ViewBag.NrPrest</div>
                    </div>
                </div>
                <div class="col">
                    @Html.LabelFor(model => model.DtVencimento, htmlAttributes: new { @class = "control-label col" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DtVencimento, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DtVencimento, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div>
            <div class="row">
                <div class="col">
                    @Html.LabelFor(model => model.Conta, "Conta", htmlAttributes: new { @class = "control-label col" })
                    <div class="col-md-10">
                        @Html.DropDownList("Conta", null, "Selecione", htmlAttributes: new { @class = "form-control", id = "Conta" })
                        @Html.ValidationMessageFor(model => model.Conta, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col">
                    @Html.LabelFor(model => model.DtPagamento, htmlAttributes: new { @class = "control-label col" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DtPagamento, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DtPagamento, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>

        <div method="post" action=".">
            <div class="row">
                <div class="col" me>
                    @Html.LabelFor(model => model.Chave, "Chave", htmlAttributes: new { @class = "control-label col" })
                    <div class="col-md-10">
                        @Html.DropDownList("Chave", null, "Selecione", htmlAttributes: new { @class = "form-control", id = "Chave" })
                        @Html.ValidationMessageFor(model => model.Chave, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col">
                    @Html.LabelFor(model => model.Valor, "Valor", htmlAttributes: new { @class = "control-label col" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control", @onkeypress = "$(this).mask('#.##0,00',{reverse: true})" } })
                        @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div>
            <div class="row">
                <div class="col">
                    @Html.LabelFor(model => model.Sequencia, "Sequencia", htmlAttributes: new { @class = "control-label col" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Sequencia, new { htmlAttributes = new { @class = "form-control", @onkeypress = "$(this).mask('0000/00')", placeholder = "9999/99" } })
                        @Html.ValidationMessageFor(model => model.Sequencia, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col">
                    @Html.LabelFor(model => model.ValorCalculado, "Valor calculado", htmlAttributes: new { @class = "control-label col" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ValorCalculado, new { htmlAttributes = new { @class = "form-control", @onkeypress = "$(this).mask('#.##0,00',{ reverse: true})" } })
                        @Html.ValidationMessageFor(model => model.ValorCalculado, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>

        <div>
            <div class="row">
                <div class="col">
                    @Html.LabelFor(model => model.FormaPagamento, "FormaPagamento", htmlAttributes: new { @class = "control-label col" })
                    <div class="col-md-10">
                        @Html.DropDownList("FormaPagamento", null, "Selecione", htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.FormaPagamento, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col">
                    @Html.LabelFor(model => model.Situacao, htmlAttributes: new { @class = "control-label col" })
                    <div class="col-md-10">
                        @Html.DropDownList("Situacao", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Situacao, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg">
                @Html.LabelFor(model => model.Obs, htmlAttributes: new { @class = "control-label col" })
                <div class="col">
                    @Html.EditorFor(model => model.Obs, new { htmlAttributes = new { @class = "form-control col-10" } })
                    @Html.ValidationMessageFor(model => model.Obs, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <hr />

        <div class="form-group">
            <input type="submit" value="Criar" class="btn btn-dark " />
            <button type="button" class="btn btn-secondary ">@Html.ActionLink("Cancelar", "Index")</button>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(document).ready(function () {
            $('#Sequencia').mask('9999/99');
        });
    </script>    
    
    <script>
        $('#Conta').change(function () {
            $.ajax({
                url: "/Prestacoes/BuscaChave",
                type: 'POST',
                dataType: "json",
                data: { Conta: $(this).val() },
                beforeSend: function () { $("#Chave").empty(); },
                error: function () { alert('A consulta falhou, tente novamente') },
                success: function (chave) {
                    for (let index in chave) {
                        let tipo = chave[index];
                        $("#Chave").append('<option value="' + tipo.Chave + '">' + tipo.Chave + '</option>');
                    };
                }
            });
        });

    </script>
}

ProjetoTCC/Views/Prestacoes/Index.cshtml
@model IEnumerable<ProjetoTCC.Prestacoes>

@{
    /**/

    ViewBag.Title = "Prestações";
}

<h2>Prestações</h2>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-dark">
        <li class="breadcrumb-item"><a href="#"><a href="#">@Html.ActionLink("Home", "Index", "Home")</a></a></li>
        <li class="breadcrumb-item active" aria-current="page">Prestações</li>
    </ol>
</nav>

<p>
    <button type="button" class="btn btn-dark ">@Html.ActionLink("Novo", "Create")</button>
    <button type="button" class="btn btn-dark ">@Html.ActionLink("Gerar prestações", "GeraPrestacoes", "GeraPrestacoes")</button>
</p>

<table class="table table-hover" id="mytable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Membros.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Conta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Chave)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sequencia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DtVencimento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Situacao)
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Membros.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Contas.Conta)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Chave)
                </td>
                <td> <!-- Sequência no formato 9999/99 -->
                    @String.Format("{0}/{1}", item.Sequencia.Substring(0, 4), @item.Sequencia.Substring(4, 2))
                </td>
                <td> <!-- Data no formato 99/99/9999 -->
                    @String.Format("{0:d}", item.DtVencimento)
                </td>

                @if (item.Situacao == "A" && item.DtVencimento > DateTime.Now)
                {
                    <td>
                        <button type="button" class="btn btn-secondary btn-sm btn-block" disabled>Em aberto</button>
                    </td>
                }
                else if (item.Situacao == "A" && item.DtVencimento <= DateTime.Now)
                {
                    <td>
                        <button type="button" class="btn btn-danger btn-sm btn-block" disabled>Vencida</button>
                    </td>
                }
                else if (item.Situacao == "P")
                {
                    <td>
                        <button type="button" class="btn btn-success btn-sm btn-block" disabled>Paga</button>
                    </td>
                }
                else
                {
                    <td>
                        <button type="button" class="btn btn-primary btn-sm btn-block" disabled>Anulada</button>
                    </td>
                }

                <td align="right">
                    <button type="button" class="btn btn-dark btn-sm">@Html.ActionLink("Editar", "Edit", new { nrPrest = item.Nrprest }) </button>
                    <button type="button" class="btn btn-dark btn-sm">@Html.ActionLink("Detalhes", "Details", new { nrPrest = item.Nrprest }) </button>
                    <button type="button" class="btn btn-dark btn-sm">@Html.ActionLink("Deletar", "Delete", new { nrPrest = item.Nrprest }) </button>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        $(document).ready(function () {
            $('#mytable').DataTable({
                "language": {
                    "url": "/Content/pt-br.json"
                }
            });
        });
    </script>
}