ProjetoTCC/Controllers/TipoChaveController.cs
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace ProjetoTCC.Controllers
{
    [Authorize]
    public class TipoChaveController : Controller
    {
        private EstudoTCCDB db = new EstudoTCCDB();

        // GET: TipoChave
        public ActionResult Index()
        {
            return View(db.TipoChave.ToList());
        }

        // GET: TipoChave/Details/5
        public ActionResult Details(string tipo)
        {
            if (tipo == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoChave tipoChave = db.TipoChave.Find(tipo);
            if (tipoChave == null)
            {
                return HttpNotFound();
            }
            return View(tipoChave);
        }

        // GET: TipoChave/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TipoChave/Create
        [HttpPost]
        public ActionResult Create([Bind(Include = "tipo, descricao, inativo")] TipoChave tipoChave)
        {
            if (ModelState.IsValid)
            {
                db.TipoChave.Add(tipoChave);
                db.SaveChanges();
                TempData["success"] = "Registro criado com sucesso";
                return RedirectToAction("Index");
            }
            return View(tipoChave);
        }

        // GET: TipoChave/Edit/5
        public ActionResult Edit(string tipo)
        {
            if (tipo == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoChave tipoChave = db.TipoChave.Find(tipo);
            if (tipoChave == null)
            {
                return HttpNotFound();
            }
            return View(tipoChave);
        }

        // POST: TipoChave/Edit/5
        [HttpPost]
        public ActionResult Edit([Bind(Include = "tipo, descricao, inativo")] TipoChave tipoChave)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tipoChave).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                TempData["success"] = "Registro editado com sucesso";
                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: TipoChave/Delete/5
        public ActionResult Delete(string tipo)
        {
            if (tipo == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoChave tipoChave = db.TipoChave.Find(tipo);
            if (tipoChave == null)
            {
                return HttpNotFound();
            }
            return View(tipoChave);
        }

        // POST: TipoChave/Delete/5
        [HttpPost]
        public ActionResult Delete(string tipo, FormCollection collection)
        {
            TipoChave tipoChave = db.TipoChave.Find(tipo);
            db.TipoChave.Remove(tipoChave);
            db.SaveChanges();
            TempData["success"] = "Registro excluído com sucesso";
            return RedirectToAction("Index");
        }
    }
}

ProjetoTCC/Views/TipoChave/Create.cshtml
@model ProjetoTCC.TipoChave

@{
    ViewBag.Title = "Criar";
}

<h2>Criar novo tipo de chave</h2>
<nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-dark">
        <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Home", "Index", "Home")</a></li>,
        <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Tipos de chave", "Index", "TipoChave")</a></li>
        <li class="breadcrumb-item active" aria-current="page">Criar</li>
    </ol>
</nav>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <hr />

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Tipo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tipo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.CheckBoxFor(model => model.Inativo)
            @Html.ValidationMessageFor(model => model.Inativo, "", new { @class = "form-check-input" })
            <label class="form-check-label" for="gridCheck">
                Inativo
            </label>
        </div>

        <hr />

        <div class="form-group">
            <input type="submit" value="Salvar" class="btn btn-dark " />
            <button type="button" class="btn btn-secondary ">@Html.ActionLink("Cancelar", "Index")</button>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjetoTCC/Views/TipoChave/Delete.cshtml
@model ProjetoTCC.TipoChave

@{
                ViewBag.Title = "Deletar";
}

<h2>Deletar tipo de chave</h2>
<nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-dark"
        <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Home", "Index", "Home")</a></li>,
        <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Tipos de chave", "Index", "TipoChave")</a></li>
        <li class="breadcrumb-item active" aria-current="page">Deletar</li>
    </ol>
</nav>

<h3>Tem certeza que deseja deletar este registro?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tipo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Inativo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Inativo)
        </dd>

    </dl>

    <hr />

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-group">
            <input type="submit" value="Deletar" class="btn btn-danger " />
            <button type="button" class="btn btn-secondary ">@Html.ActionLink("Cancelar", "Index")</button>
        </div>
    }
</div>

ProjetoTCC/Views/TipoChave/Details.cshtml
@model ProjetoTCC.TipoChave

@{
    /**/

    ViewBag.Title = "Detalhes";
}

<h2>Detalhes do tipo de chave</h2>
<nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-dark">
        <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Home", "Index", "Home")</a></li>,
        <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Tipos de chave", "Index", "TipoChave")</a></li>
        <li class="breadcrumb-item active" aria-current="page">Detalhes</li>
    </ol>
</nav>

<hr />

<div class="form-group">
    @Html.LabelFor(model => model.Tipo, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Tipo, new { htmlAttributes = new { @class = "form-control readonly", @readonly = "readonly", disabled = "disabled" } })
        @Html.ValidationMessageFor(model => model.Tipo, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control readonly", @readonly = "readonly" } })
        @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.DisplayFor(model => model.Inativo)
    @Html.ValidationMessageFor(model => model.Inativo, "", new { @class = "form-check-input" })
    <label class="form-check-label" for="gridCheck">
        Inativo
    </label>
</div>

<hr />
<p>
    <button type="button" class="btn btn-dark">@Html.ActionLink("Editar", "Edit", new { Tipo = Model.Tipo }) </button>
    <button type="button" class="btn btn-secondary ">@Html.ActionLink("Voltar", "Index") </button>
</p>

ProjetoTCC/Views/TipoChave/Edit.cshtml
@model ProjetoTCC.TipoChave

@{
    ViewBag.Title = "Editar";
}

<h2>Editar tipo de chave</h2>
<nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-dark">
        <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Home", "Index", "Home")</a></li>,
        <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Tipos de chave", "Index", "TipoChave")</a></li>
        <li class="breadcrumb-item active" aria-current="page">Editar</li>
    </ol>
</nav>

<hr />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Tipo)

        <div class="form-group">
            @Html.LabelFor(model => model.Tipo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tipo, new { htmlAttributes = new { @class = "form-control readonly", @readonly = "readonly", disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.Tipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.CheckBoxFor(model => model.Inativo)
            @Html.ValidationMessageFor(model => model.Inativo, "", new { @class = "form-check-input" })
            <label class="form-check-label" for="gridCheck">
                Inativo
            </label>
        </div>

        <hr />

        <div class="form-group">
            <input type="submit" value="Salvar" class="btn btn-dark " />
            <button type="button" class="btn btn-secondary ">@Html.ActionLink("Cancelar", "Index")</button>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjetoTCC/Views/TipoChave/Index.cshtml
@model IEnumerable<ProjetoTCC.TipoChave>

@{
    ViewBag.Title = "Tipos de chave";
}

<h2>Tipos de chave</h2>
<nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-dark">
        <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Home", "Index", "Home")</a></li>
        <li class="breadcrumb-item active" aria-current="page">Tipos de chave</li>
    </ol>
</nav>

<p>
    <button type="button" class="btn btn-dark ">@Html.ActionLink("Novo", "Create")</button>
</p>
<table class="table table-hover" id="mytable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Tipo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Inativo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Tipo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descricao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Inativo)
                </td>
                <td align="right">
                    <button type="button" class="btn btn-dark btn-sm">@Html.ActionLink("Editar", "Edit", new { Tipo = item.Tipo }) </button>
                    <button type="button" class="btn btn-dark btn-sm">@Html.ActionLink("Detalhes", "Details", new { Tipo = item.Tipo }) </button>
                    <button type="button" class="btn btn-dark btn-sm">@Html.ActionLink("Deletar", "Delete", new { Tipo = item.Tipo }) </button>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    <script type="text/javascript">
            $(document).ready(function () {
                $('#mytable').DataTable({
                    "language": {
                        "url": "/Content/pt-br.json"
                    }
                });
            });
    </script>
}