ProjetoTCC/Controllers/FaccoesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace ProjetoTCC.Controllers
{
    [Authorize]
    public class FaccoesController : Controller
    {
        private EstudoTCCDB db = new EstudoTCCDB();

        // GET: Faccoes
        public ActionResult Index()
        {
            return View(db.Faccoes.ToList());
        }

        // GET: Faccoes/Details/5
        public ActionResult Details(string chave)
        {
            if (chave == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Faccoes faccao = db.Faccoes.Find(chave);
            if (faccao == null)
            {
                return HttpNotFound();
            }
            return View(faccao);
        }

        // GET: Faccoes/Create
        public ActionResult Create()
        {
            Dropdown();
            return View();
        }

        // POST: Faccoes/Create
        [HttpPost]
        public ActionResult Create([Bind(Include = "chave, descricao, cep, endereco, numero, compl, bairro, cidade, uf, pais, inativo")] Faccoes faccoes, string cep)
        {

            faccoes.CEP = cep.Replace("-", string.Empty);

            try
            {
                if (ModelState.IsValid)
                {
                    db.Faccoes.Add(faccoes);
                    db.SaveChanges();
                    TempData["success"] = "Facção criada com sucesso";
                    return RedirectToAction("Index");
                }
                Dropdown(faccoes);
            }
            catch (SqlException e)
            {
                Console.WriteLine(e.Errors);
            }

            return View(faccoes);
        }

        // GET: Faccoes/Edit/5
        public ActionResult Edit(string Chave)
        {
            if (Chave == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Faccoes faccoes = db.Faccoes.Find(Chave);
            if (faccoes == null)
            {
                return HttpNotFound();
            }
            Dropdown();

            return View(faccoes);
        }

        // POST: Faccoes/Edit/5
        [HttpPost]
        public ActionResult Edit([Bind(Include = "chave, descricao, cep, endereco, numero, compl, bairro, cidade, uf, pais, inativo")] Faccoes faccoes)
        {
            if (ModelState.IsValid)
            {
                db.Entry(faccoes).State = EntityState.Modified;
                db.SaveChanges();
                TempData["success"] = "Facção editada com sucesso";

                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: Faccoes/Delete/5
        public ActionResult Delete(string chave)
        {
            if (chave == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Faccoes faccao = db.Faccoes.Find(chave);
            if (faccao == null)
            {
                return HttpNotFound();
            }
            return View(faccao);
        }

        // POST: Faccoes/Delete/5
        [HttpPost]
        public ActionResult Delete(string chave, FormCollection collection)
        {
            try
            {
                Faccoes faccoes = db.Faccoes.Find(chave);
                db.Faccoes.Remove(faccoes);
                db.SaveChanges();
                TempData["success"] = "Facção excluída com sucesso";
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        private void Dropdown()
        {
            ViewBag.Chave = new SelectList(db.Chaves.Where(c => c.Tipo == "Facção").Where(c => c.Inativo == false), "chave", "chave");
            ViewBag.Pais = new List<SelectListItem>
            {
                new SelectListItem {Text = "Brasil", Value = "Brasil"},
                new SelectListItem {Text = "Exterior", Value = "Exterior"}
            };
        }

        private void Dropdown(Faccoes faccoes)
        {
            ViewBag.Chave = new SelectList(db.Chaves, "chave", "chave", faccoes.Chave);
            ViewBag.Pais = new List<SelectListItem>
                {
                    new SelectListItem {Text = "Brasil", Value = "Brasil"},
                    new SelectListItem {Text = "Exterior", Value = "Exterior"}
                };
        }
    }
}

ProjetoTCC/Views/Faccoes/Create.cshtml
@model ProjetoTCC.Faccoes

@{
    ViewBag.Title = "Criar";
}

<h2>Criar facção</h2>
<nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-dark">
        <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Home", "Index", "Home")</a></li>,
        <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Facçoes", "Index", "Faccoes")</a></li>
        <li class="breadcrumb-item active" aria-current="page">Criar</li>
    </ol>
</nav>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <hr />

    <div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row">
            <div class="col-sm">
                <div class="form-group">
                    @Html.LabelFor(model => model.Chave, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("Chave", null, "Selecione", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Chave, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-sm">
                <div class="form-group">
                    @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-md">
                <label>Situação</label> <br />
                <div class="checkbox form-check-inline">
                    @Html.EditorFor(model => model.Inativo)
                    @Html.ValidationMessageFor(model => model.Inativo, "")
                </div>
                @Html.LabelFor(model => model.Inativo)
            </div>
        </div>
    </div>

    <hr />

    <div method="get" action=".">
        <h5>Endereço</h5>
        <small id="passwordHelpBlock" class="form-text text-muted">
            Digite o CEP (apenas números) e tecle TAB para preencher o endereço automaticamente.
        </small>
        <div class="row">
            <div class="col">
                @Html.LabelFor(model => model.CEP, htmlAttributes: new { @class = "control-label col" })
                <div class="col">
                    @Html.EditorFor(model => model.CEP, new { htmlAttributes = new { @class = "form-control col" } })
                    @Html.ValidationMessageFor(model => model.CEP, "", new { @class = "text-danger" })
                </div>

            </div>
            <div class="col-6">
                @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-6" })
                <div class="col ">
                    @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control col readonly disabled", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col">
                @Html.LabelFor(model => model.Numero, htmlAttributes: new { @class = "control-label col" })
                <div class="col">
                    @Html.EditorFor(model => model.Numero, new { htmlAttributes = new { @class = "form-control col" } })
                    @Html.ValidationMessageFor(model => model.Numero, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col">
                @Html.LabelFor(model => model.Compl, htmlAttributes: new { @class = "control-label col" })
                <div class="col">
                    @Html.EditorFor(model => model.Compl, new { htmlAttributes = new { @class = "form-control col" } })
                    @Html.ValidationMessageFor(model => model.Compl, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-3">
                @Html.LabelFor(model => model.Bairro, htmlAttributes: new { @class = "control-label col-3" })
                <div class="col">
                    @Html.EditorFor(model => model.Bairro, new { htmlAttributes = new { @class = "form-control col readonly", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.Bairro, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-4">
                @Html.LabelFor(model => model.Cidade, htmlAttributes: new { @class = "control-label col-4" })
                <div class="col">
                    @Html.EditorFor(model => model.Cidade, new { htmlAttributes = new { @class = "form-control col  readonly", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.Cidade, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col">
                @Html.LabelFor(model => model.UF, htmlAttributes: new { @class = "control-label col" })
                <div class="col">
                    @Html.EditorFor(model => model.UF, new { htmlAttributes = new { @class = "form-control col  readonly", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.UF, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col">
                @Html.LabelFor(model => model.Pais, htmlAttributes: new { @class = "control-label col" })
                <div class="col">
                    @Html.DropDownList("Pais", null, "Selecione", htmlAttributes: new { @class = "form-control col" })
                    @Html.ValidationMessageFor(model => model.Pais, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>

    <hr />

    <div class="form-group">
        <input type="submit" value="Criar" class="btn btn-dark " />
        <button type="button" class="btn btn-secondary ">@Html.ActionLink("Cancelar", "Index")</button>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
            $(document).ready(function () {
                $('#CEP').mask('99999-999');
            });
    </script>
}

ProjetoTCC/Views/Faccoes/Delete.cshtml
@model ProjetoTCC.Faccoes

@{
    ViewBag.Title = "Deletar";
}

<h2>Deletar facção</h2>
<nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-dark">
        <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Home", "Index", "Home")</a></li>,
        <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Facções", "Index", "Faccoes")</a></li>
        <li class="breadcrumb-item active" aria-current="page">Deletar</li>
    </ol>
</nav>

<h3>Tem certeza que deseja deletar este registro?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Chave)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Chave)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cidade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cidade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UF)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UF)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Inativo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Inativo)
        </dd>

    </dl>

    <hr />

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-group">
            <input type="submit" value="Deletar" class="btn btn-danger " />
            <button type="button" class="btn btn-secondary ">@Html.ActionLink("Cancelar", "Index")</button>
        </div>
    }
</div>

ProjetoTCC/Views/Faccoes/Details.cshtml
@model ProjetoTCC.Faccoes

@{
    ViewBag.Title = "Detalhes";
}

<h2>Detalhes da facção</h2>
<nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-dark">
        <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Home", "Index", "Home")</a></li>,
        <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Facções", "Index", "Faccoes")</a></li>
        <li class="breadcrumb-item active" aria-current="page">Detalhes</li>
    </ol>
</nav>




<div>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="row">
        <div class="col-sm">
            <div class="form-group">
                @Html.LabelFor(model => model.Chave, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Chave, new { htmlAttributes = new { @class = "form-control readonly", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.Chave, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="col-sm">
            <div class="form-group">
                @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control readonly", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="col-md">
            <label>Situação</label> <br />
            <div class="checkbox form-check-inline">
                @Html.DisplayFor(model => model.Inativo)
                @Html.ValidationMessageFor(model => model.Inativo, "")
            </div>
            @Html.LabelFor(model => model.Inativo)
        </div>
    </div>
</div>

<hr />

<div method="get" action=".">
    <h5>Endereço</h5>
    <div class="row">
        <div class="col">
            @Html.LabelFor(model => model.CEP, htmlAttributes: new { @class = "control-label col" })
            <div class="col">
                @Html.EditorFor(model => model.CEP, new { htmlAttributes = new { @class = "form-control col readonly", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.CEP, "", new { @class = "text-danger" })
            </div>

        </div>
        <div class="col-6">
            @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-6" })
            <div class="col ">
                @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control col readonly disabled", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col">
            @Html.LabelFor(model => model.Numero, htmlAttributes: new { @class = "control-label col" })
            <div class="col">
                @Html.EditorFor(model => model.Numero, new { htmlAttributes = new { @class = "form-control col readonly", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Numero, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col">
            @Html.LabelFor(model => model.Compl, htmlAttributes: new { @class = "control-label col" })
            <div class="col">
                @Html.EditorFor(model => model.Compl, new { htmlAttributes = new { @class = "form-control col readonly", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Compl, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-3">
            @Html.LabelFor(model => model.Bairro, htmlAttributes: new { @class = "control-label col-3" })
            <div class="col">
                @Html.EditorFor(model => model.Bairro, new { htmlAttributes = new { @class = "form-control col readonly", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Bairro, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-4">
            @Html.LabelFor(model => model.Cidade, htmlAttributes: new { @class = "control-label col-4" })
            <div class="col">
                @Html.EditorFor(model => model.Cidade, new { htmlAttributes = new { @class = "form-control col  readonly", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Cidade, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col">
            @Html.LabelFor(model => model.UF, htmlAttributes: new { @class = "control-label col" })
            <div class="col">
                @Html.EditorFor(model => model.UF, new { htmlAttributes = new { @class = "form-control col  readonly", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.UF, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col">
            @Html.LabelFor(model => model.Pais, htmlAttributes: new { @class = "control-label col" })
            <div class="col">
                @Html.LabelFor(model => model.Pais, null, htmlAttributes: new { @class = "form-control col readonly", @readonly = "readonly" })
                @Html.ValidationMessageFor(model => model.Pais, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
</div>

<hr />

<p>
    <button type="button" class="btn btn-dark">@Html.ActionLink("Editar", "Edit", new { chave = Model.Chave })</button>
    <button type="button" class="btn btn-secondary ">@Html.ActionLink("Voltar", "Index") </button>
</p>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
            $(document).ready(function () {
                $('#CEP').mask('99999-999');
            });
    </script>
}

ProjetoTCC/Views/Faccoes/Edit.cshtml
@model ProjetoTCC.Faccoes

@{
    ViewBag.Title = "Editar";
}

<h2>Editar facção</h2>
<nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-dark">
        <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Home", "Index", "Home")</a></li>,
        <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Facções", "Index", "Faccoes")</a></li>
        <li class="breadcrumb-item active" aria-current="page">Editar</li>
    </ol>
</nav>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <hr />

    <div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row">
            <div class="col-sm">
                <div class="form-group">
                    @Html.LabelFor(model => model.Chave, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Chave, new { htmlAttributes = new { @class = "form-control readonly", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.Chave, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-sm">
                <div class="form-group">
                    @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-md">
                <label>Situação</label> <br />
                <div class="checkbox form-check-inline">
                    @Html.EditorFor(model => model.Inativo)
                    @Html.ValidationMessageFor(model => model.Inativo, "")
                </div>
                @Html.LabelFor(model => model.Inativo)
            </div>
        </div>
    </div>

    <hr />

    <div method="get" action=".">
        <h5>Endereço</h5>
        <small id="passwordHelpBlock" class="form-text text-muted">
            Digite o CEP (apenas números) e tecle TAB para preencher o endereço automaticamente.
        </small>
        <div class="row">
            <div class="col">
                @Html.LabelFor(model => model.CEP, htmlAttributes: new { @class = "control-label col" })
                <div class="col">
                    @Html.EditorFor(model => model.CEP, new { htmlAttributes = new { @class = "form-control col" } })
                    @Html.ValidationMessageFor(model => model.CEP, "", new { @class = "text-danger" })
                </div>

            </div>
            <div class="col-6">
                @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-6" })
                <div class="col ">
                    @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control col readonly disabled", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col">
                @Html.LabelFor(model => model.Numero, htmlAttributes: new { @class = "control-label col" })
                <div class="col">
                    @Html.EditorFor(model => model.Numero, new { htmlAttributes = new { @class = "form-control col" } })
                    @Html.ValidationMessageFor(model => model.Numero, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col">
                @Html.LabelFor(model => model.Compl, htmlAttributes: new { @class = "control-label col" })
                <div class="col">
                    @Html.EditorFor(model => model.Compl, new { htmlAttributes = new { @class = "form-control col" } })
                    @Html.ValidationMessageFor(model => model.Compl, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-3">
                @Html.LabelFor(model => model.Bairro, htmlAttributes: new { @class = "control-label col-3" })
                <div class="col">
                    @Html.EditorFor(model => model.Bairro, new { htmlAttributes = new { @class = "form-control col readonly", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.Bairro, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-4">
                @Html.LabelFor(model => model.Cidade, htmlAttributes: new { @class = "control-label col-4" })
                <div class="col">
                    @Html.EditorFor(model => model.Cidade, new { htmlAttributes = new { @class = "form-control col  readonly", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.Cidade, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col">
                @Html.LabelFor(model => model.UF, htmlAttributes: new { @class = "control-label col" })
                <div class="col">
                    @Html.EditorFor(model => model.UF, new { htmlAttributes = new { @class = "form-control col  readonly", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.UF, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col">
                @Html.LabelFor(model => model.Pais, htmlAttributes: new { @class = "control-label col" })
                <div class="col">
                    @Html.DropDownListFor(model => model.Pais, null, htmlAttributes: new { @class = "form-control col" })
                    @Html.ValidationMessageFor(model => model.Pais, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>

    <hr />

    <div class="form-group">
        <input type="submit" value="Salvar" class="btn btn-dark " />
        <button type="button" class="btn btn-secondary ">@Html.ActionLink("Cancelar", "Index")</button>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
            $(document).ready(function () {
                $('#CEP').mask('99999-999');
            });
    </script>
}

ProjetoTCC/Views/Faccoes/Index.cshtml
@model IEnumerable<ProjetoTCC.Faccoes>

@{
    ViewBag.Title = "Index";
}

<h2>Facções</h2>
<nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-dark">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Facções</li>
    </ol>
</nav>

<p>
    <button type="button" class="btn btn-dark ">@Html.ActionLink("Novo", "Create")</button>
</p>
<table class="table table-hover" id="mytable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Chaves.Chave)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cidade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UF)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Inativo)
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Chaves.Chave)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descricao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cidade)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UF)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Inativo)
                </td>
                <td align="right">
                    <button type="button" class="btn btn-dark btn-sm">@Html.ActionLink("Editar", "Edit", new { chave = item.Chave }) </button>
                    <button type="button" class="btn btn-dark btn-sm">@Html.ActionLink("Detalhes", "Details", new { chave = item.Chave }) </button>
                    <button type="button" class="btn btn-dark btn-sm">@Html.ActionLink("Deletar", "Delete", new { chave = item.Chave }) </button>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    <script type="text/javascript">
            $(document).ready(function () {
                $('#mytable').DataTable({
                    "language": {
                        "url": "/Content/pt-br.json"
                    }
                });
            });
    </script>
}