ProjetoTCC/Controllers/ParametrosController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace ProjetoTCC.Controllers
{
    [Authorize]
    public class ParametrosController : Controller
    {
        private EstudoTCCDB db = new EstudoTCCDB();

        // GET: Parametros
        public ActionResult Index()
        {
            return View(db.Parametros.ToList());
        }

        // GET: Parametros/Details/5
        public ActionResult Details(string CNPJ)
        {
            CNPJ = Functions.BuscaParametro();

            if (CNPJ == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Parametros param = db.Parametros.Find(CNPJ);
            if (param == null)
            {
                return HttpNotFound();
            }
            return View(param);
        }

        // GET: Parametros/Create
        public ActionResult Create()
        {
            Dropdown();
            return View();
        }

        // POST: Parametros/Create
        [HttpPost]
        public ActionResult Create([Bind(Include = "RazaoSocial,Clube,Sigla,CNPJ,CEP,Endereco,Numero,Compl,Bairro,Cidade,UF,Pais")] Parametros param, string CEP, string CNPJ)
        {
            try
            {
                RemoveMascara(param, CEP, CNPJ);

                if (ModelState.IsValid)
                {
                    db.Parametros.Add(param);
                    db.SaveChanges();
                    TempData["success"] = "Parâmetro registrado com sucesso";
                    return RedirectToAction("Index");
                }
                Dropdown(param);
            }
            catch (DbEntityValidationException e)
            {
                foreach (var eve in e.EntityValidationErrors)
                {
                    Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                        eve.Entry.Entity.GetType().Name, eve.Entry.State);
                    foreach (var ve in eve.ValidationErrors)
                    {
                        Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"",
                            ve.PropertyName, ve.ErrorMessage);
                    }
                }
                throw;
            }
            return View(param);
        }

        // GET: Parametros/Edit/5
        public ActionResult Edit(string CNPJ)
        {
            if (CNPJ == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Parametros param = db.Parametros.Find(CNPJ);
            if (param == null)
            {
                return HttpNotFound();
            }

            Dropdown();
            return View(param);
        }

        // POST: Parametros/Edit/5
        [HttpPost]
        public ActionResult Edit([Bind(Include = "RazaoSocial,Clube,Sigla,CNPJ,CEP,Endereco,Numero,Compl,Bairro,Cidade,UF,Pais")] Parametros param, string CEP, string CNPJ)
        {
            try
            {
                RemoveMascara(param, CEP, CNPJ);

                if (ModelState.IsValid)
                {
                    db.Entry(param).State = EntityState.Modified;
                    db.SaveChanges();
                    TempData["success"] = "Parâmetro editado com sucesso";
                    return RedirectToAction("Details");
                }
                Dropdown(param);
                return View();
            }
            catch (DbEntityValidationException e)
            {
                foreach (var eve in e.EntityValidationErrors)
                {
                    Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                        eve.Entry.Entity.GetType().Name, eve.Entry.State);
                    foreach (var ve in eve.ValidationErrors)
                    {
                        Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"",
                            ve.PropertyName, ve.ErrorMessage);
                    }
                }
                throw;
            }
        }

        private void Dropdown()
        {
            ViewBag.Pais = new List<SelectListItem>
            {
                new SelectListItem {Text = "Brasil", Value = "Brasil"},
                new SelectListItem {Text = "Exterior", Value = "Exterior"}
            };
        }

        private void Dropdown(Parametros param)
        {
            ViewBag.Pais = new List<SelectListItem>
            {
                new SelectListItem {Text = "Brasil", Value = "Brasil"},
                new SelectListItem {Text = "Exterior", Value = "Exterior"}
            };
        }

        private static void RemoveMascara(Parametros param, string cep, string cnpj)
        {
            param.CEP = cep.Replace("-", string.Empty);
            param.CNPJ = cnpj.Replace(".", string.Empty).Replace("-", string.Empty).Replace("/", string.Empty);            
        }

        [HttpPost]
        public JsonResult ValidaCNPJ(string CNPJ)
        {
            bool retorno = Functions.ValidaCPFCNPJ(CNPJ);

            return Json(retorno, JsonRequestBehavior.AllowGet);
        }
    }
}

ProjetoTCC/Views/Parametros/Create.cshtml
@model ProjetoTCC.Parametros

@{
    ViewBag.Title = "Criar";
}

<h2>Criar novo Parâmetro</h2>
<nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-dark">
        <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Home", "Index", "Home")</a></li>,
        <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Parâmetros", "Index", "Parametros")</a></li>
        <li class="breadcrumb-item active" aria-current="page">Criar</li>
    </ol>
</nav>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <hr />

    <div>
        <div>
            <h5>Clube</h5>
            <div class="row">
                <div class="col">
                    @Html.LabelFor(model => model.Clube, htmlAttributes: new { @class = "control-label col" })
                    <div class="col">
                        @Html.EditorFor(model => model.Clube, new { htmlAttributes = new { @class = "form-control col" } })
                        @Html.ValidationMessageFor(model => model.Clube, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col">
                    @Html.LabelFor(model => model.Sigla, htmlAttributes: new { @class = "control-label col" })
                    <div class="col">
                        @Html.EditorFor(model => model.Sigla, new { htmlAttributes = new { @class = "form-control col" } })
                        @Html.ValidationMessageFor(model => model.Sigla, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div>
            <div class="row">
                <div class="col">
                    @Html.LabelFor(model => model.RazaoSocial, htmlAttributes: new { @class = "control-label col" })
                    <div class="col">
                        @Html.EditorFor(model => model.RazaoSocial, new { htmlAttributes = new { @class = "form-control col" } })
                        @Html.ValidationMessageFor(model => model.RazaoSocial, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col">
                    @Html.LabelFor(model => model.CNPJ, htmlAttributes: new { @class = "control-label col" })
                    <div class="col">
                        @Html.EditorFor(model => model.CNPJ, new { htmlAttributes = new { @class = "form-control col" } })
                        @Html.ValidationMessageFor(model => model.CNPJ, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>

        <hr />

        <div method="get" action=".">
            <h5>Endereço</h5>
            <small id="passwordHelpBlock" class="form-text text-muted">
                Digite o CEP (apenas números) e tecle TAB para preencher o endereço automaticamente.
            </small>
            <div class="row">
                <div class="col">
                    @Html.LabelFor(model => model.CEP, "CEP", htmlAttributes: new { @class = "control-label col" })
                    <div class="col">
                        @Html.EditorFor(model => model.CEP, new { htmlAttributes = new { @class = "form-control col", placeholder = "99999-999" } })
                        @Html.ValidationMessageFor(model => model.CEP, "", new { @class = "text-danger" })
                    </div>

                </div>
                <div class="col-6">
                    @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-6" })
                    <div class="col ">
                        @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control col readonly", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col">
                    @Html.LabelFor(model => model.Numero, htmlAttributes: new { @class = "control-label col" })
                    <div class="col">
                        @Html.EditorFor(model => model.Numero, new { htmlAttributes = new { @class = "form-control col" } })
                        @Html.ValidationMessageFor(model => model.Numero, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col">
                    @Html.LabelFor(model => model.Compl, htmlAttributes: new { @class = "control-label col" })
                    <div class="col">
                        @Html.EditorFor(model => model.Compl, new { htmlAttributes = new { @class = "form-control col" } })
                        @Html.ValidationMessageFor(model => model.Compl, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-3">
                    @Html.LabelFor(model => model.Bairro, htmlAttributes: new { @class = "control-label col-3" })
                    <div class="col">
                        @Html.EditorFor(model => model.Bairro, new { htmlAttributes = new { @class = "form-control col  readonly", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.Bairro, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-4">
                    @Html.LabelFor(model => model.Cidade, htmlAttributes: new { @class = "control-label col-4" })
                    <div class="col">
                        @Html.EditorFor(model => model.Cidade, new { htmlAttributes = new { @class = "form-control col  readonly", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.Cidade, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col">
                    @Html.LabelFor(model => model.UF, htmlAttributes: new { @class = "control-label col" })
                    <div class="col">
                        @Html.EditorFor(model => model.UF, new { htmlAttributes = new { @class = "form-control col  readonly", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.UF, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col">
                    @Html.LabelFor(model => model.Pais, htmlAttributes: new { @class = "control-label col" })
                    <div class="col">
                        @Html.DropDownList("Pais", null, "Selecione", htmlAttributes: new { @class = "form-control col" })
                        @Html.ValidationMessageFor(model => model.Pais, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
    </div>

    <hr />

    <div class="form-group">
        <input type="submit" value="Criar" class="btn btn-dark " />
        <button type="button" class="btn btn-secondary ">@Html.ActionLink("Cancelar", "Index")</button>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            $('#CEP').mask('99999-999');
            $('#CNPJ').mask('99.999.999/9999-99');
        });
    </script>
}

ProjetoTCC/Views/Parametros/Details.cshtml
@model ProjetoTCC.Parametros

@{
    ViewBag.Title = "Detalhes";
}

<h2>Parâmetros</h2>
<nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-dark">
        <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Home", "Index", "Home")</a></li>
        <li class="breadcrumb-item active" aria-current="page">Parâmetros</li>
    </ol>
</nav>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <hr />

    <div>
        <div>
            <h5>Sistema registrado para:</h5>
            <div class="row">
                <div class="col">
                    @Html.LabelFor(model => model.Clube, htmlAttributes: new { @class = "control-label col" })
                    <div class="col">
                        @Html.EditorFor(model => model.Clube, new { htmlAttributes = new { @class = "form-control col readonly", @readonly = "readonly" } })
                    </div>
                </div>
                <div class="col">
                    @Html.LabelFor(model => model.Sigla, htmlAttributes: new { @class = "control-label col" })
                    <div class="col">
                        @Html.EditorFor(model => model.Sigla, new { htmlAttributes = new { @class = "form-control col readonly", @readonly = "readonly" } })
                    </div>
                </div>
            </div>
        </div>
        <div>
            <div class="row">
                <div class="col">
                    @Html.LabelFor(model => model.RazaoSocial, htmlAttributes: new { @class = "control-label col" })
                    <div class="col">
                        @Html.EditorFor(model => model.RazaoSocial, new { htmlAttributes = new { @class = "form-control col readonly", @readonly = "readonly" } })
                    </div>
                </div>
                <div class="col">
                    @Html.LabelFor(model => model.CNPJ, htmlAttributes: new { @class = "control-label col" })
                    <div class="col">
                        @Html.EditorFor(model => model.CNPJ, new { htmlAttributes = new { @class = "form-control col readonly", @readonly = "readonly" } })
                    </div>
                </div>
            </div>
        </div>

        <hr />

        <div>
            <h5>Endereço</h5>
            <div class="row">
                <div class="col">
                    @Html.LabelFor(model => model.CEP, "CEP", htmlAttributes: new { @class = "control-label col" })
                    <div class="col">
                        @Html.EditorFor(model => model.CEP, new { htmlAttributes = new { @class = "form-control col readonly", @readonly = "readonly" } })
                    </div>

                </div>
                <div class="col-6">
                    @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-6" })
                    <div class="col ">
                        @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control col readonly", @readonly = "readonly" } })
                    </div>
                </div>
                <div class="col">
                    @Html.LabelFor(model => model.Numero, htmlAttributes: new { @class = "control-label col" })
                    <div class="col">
                        @Html.EditorFor(model => model.Numero, new { htmlAttributes = new { @class = "form-control col readonly", @readonly = "readonly" } })
                    </div>
                </div>
                <div class="col">
                    @Html.LabelFor(model => model.Compl, htmlAttributes: new { @class = "control-label col" })
                    <div class="col">
                        @Html.EditorFor(model => model.Compl, new { htmlAttributes = new { @class = "form-control col readonly", @readonly = "readonly" } })
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-3">
                    @Html.LabelFor(model => model.Bairro, htmlAttributes: new { @class = "control-label col-3" })
                    <div class="col">
                        @Html.EditorFor(model => model.Bairro, new { htmlAttributes = new { @class = "form-control col  readonly", @readonly = "readonly" } })
                    </div>
                </div>
                <div class="col-4">
                    @Html.LabelFor(model => model.Cidade, htmlAttributes: new { @class = "control-label col-4" })
                    <div class="col">
                        @Html.EditorFor(model => model.Cidade, new { htmlAttributes = new { @class = "form-control col  readonly", @readonly = "readonly" } })
                    </div>
                </div>
                <div class="col">
                    @Html.LabelFor(model => model.UF, htmlAttributes: new { @class = "control-label col" })
                    <div class="col">
                        @Html.EditorFor(model => model.UF, new { htmlAttributes = new { @class = "form-control col  readonly", @readonly = "readonly" } })
                    </div>
                </div>
                <div class="col">
                    @Html.LabelFor(model => model.Pais, htmlAttributes: new { @class = "control-label col" })
                    <div class="col">
                        @Html.EditorFor(model => model.Pais, new { htmlAttributes = new { @class = "form-control readonly", @readonly = "readonly" } })
                    </div>
                </div>
            </div>
        </div>
    </div>

    <hr />

    <p>
        <button type="button" class="btn btn-dark">@Html.ActionLink("Editar", "Edit", new { CNPJ = Model.CNPJ })</button>
        <button type="button" class="btn btn-secondary ">@Html.ActionLink("Home", "Index", "Home") </button>
    </p>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            $('#CEP').mask('99999-999');
            $('#CNPJ').mask('99.999.999/9999-99');
        });
    </script>
}

ProjetoTCC/Views/Parametros/Edit.cshtml
@model ProjetoTCC.Parametros

@{
    ViewBag.Title = "Editar";
}

<h2>Editar parâmetro</h2>
<nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-dark">
        <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Home", "Index", "Home")</a></li>,
        <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Parâmetros", "Details", "Parametros")</a></li>
        <li class="breadcrumb-item active" aria-current="page">Editar</li>
    </ol>
</nav>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <hr />

    <div>
        <div>
            <h5>Clube</h5>
            <div class="row">
                <div class="col">
                    @Html.LabelFor(model => model.Clube, htmlAttributes: new { @class = "control-label col" })
                    <div class="col">
                        @Html.EditorFor(model => model.Clube, new { htmlAttributes = new { @class = "form-control col" } })
                        @Html.ValidationMessageFor(model => model.Clube, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col">
                    @Html.LabelFor(model => model.Sigla, htmlAttributes: new { @class = "control-label col" })
                    <div class="col">
                        @Html.EditorFor(model => model.Sigla, new { htmlAttributes = new { @class = "form-control col" } })
                        @Html.ValidationMessageFor(model => model.Sigla, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div>
            <div class="row">
                <div class="col">
                    @Html.LabelFor(model => model.RazaoSocial, htmlAttributes: new { @class = "control-label col" })
                    <div class="col">
                        @Html.EditorFor(model => model.RazaoSocial, new { htmlAttributes = new { @class = "form-control col" } })
                        @Html.ValidationMessageFor(model => model.RazaoSocial, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col">
                    @Html.LabelFor(model => model.CNPJ, htmlAttributes: new { @class = "control-label col" })
                    <div class="col">
                        @Html.EditorFor(model => model.CNPJ, new { htmlAttributes = new { @class = "form-control col" } })
                        @Html.ValidationMessageFor(model => model.CNPJ, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>

        <hr />

        <div method="get" action=".">
            <h5>Endereço</h5>
            <small id="passwordHelpBlock" class="form-text text-muted">
                Digite o CEP (apenas números) e tecle TAB para preencher o endereço automaticamente.
            </small>
            <div class="row">
                <div class="col">
                    @Html.LabelFor(model => model.CEP, "CEP", htmlAttributes: new { @class = "control-label col" })
                    <div class="col">
                        @Html.EditorFor(model => model.CEP, new { htmlAttributes = new { @class = "form-control col", placeholder = "99999-999" } })
                        @Html.ValidationMessageFor(model => model.CEP, "", new { @class = "text-danger" })
                    </div>

                </div>
                <div class="col-6">
                    @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-6" })
                    <div class="col ">
                        @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control col readonly", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col">
                    @Html.LabelFor(model => model.Numero, htmlAttributes: new { @class = "control-label col" })
                    <div class="col">
                        @Html.EditorFor(model => model.Numero, new { htmlAttributes = new { @class = "form-control col" } })
                        @Html.ValidationMessageFor(model => model.Numero, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col">
                    @Html.LabelFor(model => model.Compl, htmlAttributes: new { @class = "control-label col" })
                    <div class="col">
                        @Html.EditorFor(model => model.Compl, new { htmlAttributes = new { @class = "form-control col" } })
                        @Html.ValidationMessageFor(model => model.Compl, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-3">
                    @Html.LabelFor(model => model.Bairro, htmlAttributes: new { @class = "control-label col-3" })
                    <div class="col">
                        @Html.EditorFor(model => model.Bairro, new { htmlAttributes = new { @class = "form-control col  readonly", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.Bairro, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-4">
                    @Html.LabelFor(model => model.Cidade, htmlAttributes: new { @class = "control-label col-4" })
                    <div class="col">
                        @Html.EditorFor(model => model.Cidade, new { htmlAttributes = new { @class = "form-control col  readonly", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.Cidade, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col">
                    @Html.LabelFor(model => model.UF, htmlAttributes: new { @class = "control-label col" })
                    <div class="col">
                        @Html.EditorFor(model => model.UF, new { htmlAttributes = new { @class = "form-control col  readonly", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.UF, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col">
                    @Html.LabelFor(model => model.Pais, htmlAttributes: new { @class = "control-label col" })
                    <div class="col">
                        @Html.DropDownListFor(model => model.Pais, null, htmlAttributes: new { @class = "form-control col" })
                        @Html.ValidationMessageFor(model => model.Pais, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
    </div>

    <hr />

    <div class="form-group">
        <input type="submit" value="Salvar" class="btn btn-dark " />
        <button type="button" class="btn btn-secondary ">@Html.ActionLink("Cancelar", "Details")</button>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            $('#CEP').mask('99999-999');
            $('#CNPJ').mask('99.999.999/9999-99');
        });
    </script>
}

ProjetoTCC/Views/Parametros/Index.cshtml
@model IEnumerable<ProjetoTCC.Parametros>

@{
    ViewBag.Title = "Parâmetros";
}

<h2>Parâmetros</h2>
<nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-dark">
        <li class="breadcrumb-item"><a href="#">@Html.ActionLink("Home", "Index", "Home")</a></li>
        <li class="breadcrumb-item active" aria-current="page">Parâmetros</li>
    </ol>
</nav>

<p>
    <button type="button" class="btn btn-dark ">@Html.ActionLink("Novo", "Create")</button>
</p>

<table class="table table-hover" id="mytable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RazaoSocial)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Clube)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sigla)
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.RazaoSocial)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Clube)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Sigla)
                </td>
                <td align="right">
                    <button type="button" class="btn btn-dark btn-sm">@Html.ActionLink("Editar", "Edit", new { CNPJ = item.CNPJ }) </button>
                    <button type="button" class="btn btn-dark btn-sm">@Html.ActionLink("Detalhes", "Details", new { CNPJ = item.CNPJ }) </button>
                    <button type="button" class="btn btn-dark btn-sm">@Html.ActionLink("Deletar", "Delete", new { CNPJ = item.CNPJ }) </button>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
            $('#mytable').DataTable({
                "language": {
                    "url": "/Content/pt-br.json"
                }
            });
        });
    </script>
}